apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: mariadb-backup
spec:
  schedule: "*/5 * * * *"
  task:
    name: mariadb-backup-10.5.8
  repository:
    name: local-repo-with-hostpath
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: mariadb
  retentionPolicy:
    name: keep-last-5
    keepLast: 5
    prune: true