apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatcloud-back
spec:
  restartPolicy: Always
  selector:
    matchLabels:
      app: chatcloud-back
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: chatcloud-back
    spec:
      containers:
      - image: dramanedev/backend-app
        name: chatcloud-back
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 20m
            memory: 20Mi
        ports:
        - containerPort: 3000
          name: chatcloud-back
        env:
        - name: DB_NAME
          value: "chatcloud"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username
        - name: DB_PWD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
        - name: DB_HOST
          value: "mariadb"
        - name: REDIS_HOST
          value: "redis"
        - name: SERVER_PORT
          value: "3000"