apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-initdb-config
data:
  initdb.sql: |
    CREATE TABLE `loggedUsers` (
      `id` int(11) NOT NULL,
      `username` varchar(255) NOT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
    CREATE TABLE `messages` (
      `id` int(11) NOT NULL,
      `username` varchar(255) NOT NULL,
      `message` text NOT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
    ALTER TABLE `loggedUsers`
      ADD PRIMARY KEY (`id`),
      ADD UNIQUE KEY `username` (`username`);
    ALTER TABLE `messages`
      ADD PRIMARY KEY (`id`);
    ALTER TABLE `loggedUsers`
      MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=46;
    ALTER TABLE `messages`
      MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
