apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatcloud-front
spec:
  selector:
    matchLabels:
      app: chatcloud-front
  replicas: 1
  template:
    metadata:
      labels:
        app: chatcloud-front
    spec:
      containers:
      - name: chatcloud-front
        image: dramanedev/angular-app
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 20m
            memory: 20Mi
        ports:
        - containerPort: 80
          name: chatcloud-front
        volumeMounts:
        - name: config-env
          mountPath: /usr/share/nginx/html/config/
        livenessProbe:
          httpGet:
            path: /
            port: chatcloud-front
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: chatcloud-front
          initialDelaySeconds: 3
      volumes:
      - name: config-env
        configMap:
          name: config-env