apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatcloud-front
spec:
  selector:
    matchLabels:
      app: chatcloud-front
  replicas: 1
  template:
    metadata:
      labels:
        app: chatcloud-front
    spec:
      containers:
      - name: chatcloud-front
        image: dramanedev/angular-app
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-env
          mountPath: /usr/share/nginx/html/config/
      volumes:
      - name: config-env
        configMap:
          name: config-env